/**
 * Task 08: this is the one seam the whole CMS-to-public-website bridge
 * hinges on. Every consumer of Project data goes through
 * `services/content/projects.service.ts`, which only ever imports
 * `{ projects }` from this file — never from `projects.data.ts`
 * directly, and never a Prisma/CMS import of any kind (see that
 * service's own doc comment). That indirection is exactly what lets
 * this one line change the data source for the entire public site.
 *
 * `projects.json` is generated by `cms/scripts/export-content.ts`
 * (`npm run content:export`, run from `cms/`) and is regenerated
 * wholesale on every export — it is derived output, not something to
 * hand-edit. `projects.data.ts` is no longer imported by anything; it's
 * left in place as the pre-CMS authoring history, not as a fallback (if
 * `generated/projects.json` is ever deleted, run `npm run content:export`
 * from `cms/` to regenerate it — that's still the single source of
 * truth now, not this file).
 *
 * The cast is necessary, not just decorative: TypeScript infers a
 * JSON import's type structurally from the literal file content (e.g.
 * a string literal union collapses to `string`, and a field absent on
 * every current item infers as never-present rather than optional), so
 * it can never line up with the hand-written `Project` interface
 * exactly. `export-content.ts` is what actually guarantees the JSON's
 * shape is correct — see that script's own validation pass — this cast
 * just tells TypeScript to trust that already-validated guarantee
 * rather than re-deriving an incompatible structural type from the
 * JSON literal.
 */
import generatedProjects from "../generated/projects.json";
import type { Project } from "@/types/content";

export const projects = generatedProjects as unknown as Project[];
